Knock-and-knock/backend

- .dockerignore
- .github/workflows/main.yml
- Dockerfile
- build.gradle
- src/main/java/com/shinhan/knockknock/domain/entity/TestEntity.java
- Dockerfile 제작
- .dockerignore 제작
- workflow 추가
> [Deploy] Github action을 위한 workflow 제작

- .github/workflows/main.yml
- IMAGE_NAME 수정
- CONTAINER_NAME 수정
> [Refactor] workflow 수정

- .gitignore
- build.gradle
- src/main/java/com/shinhan/knockknock/controller/SwaggerTestController.java
- src/main/java/com/shinhan/knockknock/swagger/SwaggerConfig.java
-  openapi dependency 추가
- swagger config 제작
- annotation 테스트
> 🌟(#4) Swagger 테스트

- gradle/wrapper/gradle-wrapper.properties
> Feat welfare table

- src/main/java/com/shinhan/knockknock/domain/entity/CardCategoryEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardHistoryEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardIssueEntity.java
- src/main/resources/application.properties
-  CardIssueEntity 생성
-  CardEntity 생성
-  CardHistoryEntity 생성
-  CardCategoryEntity 생성
> [Feat] Card Entity 생성

- src/main/java/com/shinhan/knockknock/controller/CardIssueRestController.java
- src/main/java/com/shinhan/knockknock/domain/dto/CreateCardIssueRequest.java
- src/main/java/com/shinhan/knockknock/domain/dto/CreateCardResponse.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardCategoryEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardHistoryEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardIssueEntity.java
- src/main/java/com/shinhan/knockknock/repository/CardIssueRepository.java
- src/main/java/com/shinhan/knockknock/repository/CardRepository.java
- src/main/java/com/shinhan/knockknock/service/CardIssueService.java
- src/main/java/com/shinhan/knockknock/service/CardIssueServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/CardService.java
- src/main/java/com/shinhan/knockknock/service/CardServiceImpl.java
- src/main/resources/application.properties
- CreateCardIssueRequest 생성 및 구현
- CreateCardResponse 생성 및 구현
- CardIssueService 인터페이스 생성 및 구현
- CardIssueServiceImpl 클래스 생성 및 구현
- CardIssueRepository 클래스 생성 및 구현
- CardIssueRestController 클래스 생성 및 구현
- CreateCardResponse 생성 및 구현
- CardService, CardServiceImpl 구현
- CardRepository 생성 및 구현
- Controller는 요청만 매칭해주고 Service에서 비즈니스 로직 구현
- RestController에서 /card/apply로 들어온 body 정보 CardIssueServiceImpl 로 전달 
- CreateCardRequest를 Entity 타입으로 변환하고 CardIssueEntity 생성
- 요청정보로 CardEntity 생성하기 위해 CardIssueServiceImpl에서 cardServiceImpl의 createCard 수행
- 카드번호, cvc 발급한 후, 카드 정보 CreateCardResponse DTO타입으로 변환하고 반환
- 전체적인 추가 수정 예정
> [Feat] 카드 발급 기능 구현

- src/main/java/com/shinhan/knockknock/config/EnvConfig.java
- src/main/java/com/shinhan/knockknock/domain/dto/CreateUserRequest.java
- src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
- UserEntity 생성
- CreateUserRequest 생성
> [Feat] User domain 생성

- src/main/java/com/shinhan/knockknock/controller/WelfareController.java
- src/main/java/com/shinhan/knockknock/domain/dto/WelfareBookRequest.java
- src/main/java/com/shinhan/knockknock/domain/dto/WelfareBookResponse.java
- src/main/java/com/shinhan/knockknock/domain/dto/WelfareRequest.java
- src/main/java/com/shinhan/knockknock/domain/dto/WelfareResponse.java
- src/main/java/com/shinhan/knockknock/domain/entity/WelfareBookEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/WelfareEntity.java
- src/main/java/com/shinhan/knockknock/repository/WelfareBookRepository.java
- src/main/java/com/shinhan/knockknock/repository/WelfareRepository.java
- src/main/java/com/shinhan/knockknock/service/WelfareBookService.java
- src/main/java/com/shinhan/knockknock/service/WelfareBookServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/WelfareService.java
- src/main/java/com/shinhan/knockknock/service/WelfareServiceImpl.java
- entity 생성
- response, request생성
- service 생성
> 🌟(#11 ) 복지, 복지예약

- src/main/java/com/shinhan/knockknock/controller/WelfareController.java
- src/main/java/com/shinhan/knockknock/domain/dto/CreateWelfareBookRequest.java
- src/main/java/com/shinhan/knockknock/domain/dto/CreateWelfareRequest.java
- src/main/java/com/shinhan/knockknock/domain/dto/ReadWelfareBookResponse.java
- src/main/java/com/shinhan/knockknock/domain/dto/ReadWelfareResponse.java
- src/main/java/com/shinhan/knockknock/domain/entity/WelfareBookEntity.java
- src/main/java/com/shinhan/knockknock/restcontroller/WelfareBookRestController.java
- src/main/java/com/shinhan/knockknock/restcontroller/WelfareRestController.java
- src/main/java/com/shinhan/knockknock/service/WelfareBookService.java
- src/main/java/com/shinhan/knockknock/service/WelfareBookServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/WelfareService.java
- src/main/java/com/shinhan/knockknock/service/WelfareServiceImpl.java
> 🌟(#11 ) 복지, 복지예약 restcontroller

- src/main/java/com/shinhan/knockknock/config/AsyncConfig.java
- src/main/java/com/shinhan/knockknock/controller/CardIssueRestController.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardIssueEntity.java
- src/main/java/com/shinhan/knockknock/service/CardIssueServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/CardService.java
- src/main/java/com/shinhan/knockknock/service/CardServiceImpl.java
- 스레드풀 사용한 카드 발급 비동기 처리 ( 1분으로 설정됨 )
- 동시에 n개의 카드 발급 신청 테스트 완료
- NotNull 어노테이션으로 교체
> 🌟(#27 ) 카드 발급 비동기 처리

- build.gradle
- src/main/java/com/shinhan/knockknock/config/AsyncConfig.java
- src/main/java/com/shinhan/knockknock/controller/CardIssueRestController.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardHistoryEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardIssueEntity.java
- src/main/java/com/shinhan/knockknock/service/CardIssueServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/CardService.java
- src/main/java/com/shinhan/knockknock/service/CardServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/ClovaOCRService.java
- src/main/resources/application.properties
- 신분증 OCR 구현 완료
- 페이지 얘기 안했어서 보류
> 🌟(#29 ) 신분증 OCR 구현 외 보류

- build.gradle
- src/main/java/com/shinhan/knockknock/config/SecurityConfig.java
- src/main/java/com/shinhan/knockknock/controller/UserController.java
- src/main/java/com/shinhan/knockknock/domain/dto/CreateUserRequest.java
- src/main/java/com/shinhan/knockknock/domain/dto/UserValidationResponse.java
- src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/UserRole.java
- src/main/java/com/shinhan/knockknock/repository/UserRepository.java
- src/main/java/com/shinhan/knockknock/service/UserService.java
- src/main/java/com/shinhan/knockknock/service/UserServiceImpl.java
- src/main/resources/application.properties
- src/test/java/com/shinhan/knockknock/UserControllerTest.java
- 아이디 중복 체크 구현
- 전화번호 인증 구현
- 회원가입 구현
- Spring Security 추가
> 🌟(#18 ) 회원가입 구현

- build.gradle
- src/main/java/com/shinhan/knockknock/auth/CustomUserDetails.java
- src/main/java/com/shinhan/knockknock/auth/JwtAuthenticationFilter.java
- src/main/java/com/shinhan/knockknock/auth/JwtProvider.java
- src/main/java/com/shinhan/knockknock/config/SecurityConfig.java
- src/main/java/com/shinhan/knockknock/controller/AuthController.java
- src/main/java/com/shinhan/knockknock/controller/UserController.java
- src/main/java/com/shinhan/knockknock/domain/dto/CreateUserRequest.java
- src/main/java/com/shinhan/knockknock/domain/dto/LoginUserRequest.java
- src/main/java/com/shinhan/knockknock/domain/dto/LoginUserResponse.java
- src/main/java/com/shinhan/knockknock/domain/dto/TokenResponse.java
- src/main/java/com/shinhan/knockknock/domain/dto/UserValidationResponse.java
- src/main/java/com/shinhan/knockknock/domain/entity/TokenEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/UserRole.java
- src/main/java/com/shinhan/knockknock/repository/TokenRepository.java
- src/main/java/com/shinhan/knockknock/repository/UserRepository.java
- src/main/java/com/shinhan/knockknock/service/AuthService.java
- src/main/java/com/shinhan/knockknock/service/CustomUserDetailsService.java
- src/main/java/com/shinhan/knockknock/service/UserService.java
- src/main/java/com/shinhan/knockknock/service/UserServiceImpl.java
- src/main/resources/application.properties
- src/test/java/com/shinhan/knockknock/UserControllerTest.java
> 🌟(#35 ) 로그인 구현

- src/main/java/com/shinhan/knockknock/controller/ConversationLogController.java
- src/main/java/com/shinhan/knockknock/controller/ConversationRoomController.java
- src/main/java/com/shinhan/knockknock/domain/dto/conversationroom/ConversationLogRequest.java
- src/main/java/com/shinhan/knockknock/domain/dto/conversationroom/ConversationLogResponse.java
- src/main/java/com/shinhan/knockknock/domain/entity/ConversationLogEntity.java
- src/main/java/com/shinhan/knockknock/service/ConversationLogService.java
- src/main/java/com/shinhan/knockknock/service/ConversationLogServiceImpl.java
- Conversation Log service 추가
- Conversation Log controller 추가
> 🌟(#40 ) Conversation Log CRUD 추가

- src/main/java/com/shinhan/knockknock/config/SecurityConfig.java
- src/main/java/com/shinhan/knockknock/config/SwaggerConfig.java
- src/main/resources/application.properties
- src/test/java/com/shinhan/knockknock/service/WelfareServiceTest.java
- src/test/resources/application-test.properties
- Swagger config 수정
- test db setting 추가
> 🌟(#49 ) Swagger config 수정 및 test db setting 추가

- .github/workflows/main.yml
> 🌟(#3 ) workflow 수정

- Dockerfile
> 🌟(#3 ) Dockerfile 수정

- Dockerfile
> 🌟(#3 ) Dockerfile 업데이트

- Dockerfile
- src/main/java/com/shinhan/knockknock/config/EnvConfig.java
> 🌟(#3 ) EnvConfig 수정

- Dockerfile
> 🌟(#3 ) Dockerfile rollback

- .github/workflows/main.yml
> 🌟(#3 ) main.yml 수정

- src/test/java/com/shinhan/knockknock/service/ConversationLogTest.java
- src/test/java/com/shinhan/knockknock/service/ConversationRoomTest.java
> 🌟(#49 ) 대화 관련 테스트 코드 추가

- src/main/java/com/shinhan/knockknock/controller/CardController.java
- src/main/java/com/shinhan/knockknock/domain/entity/NotificationEntity.java
> 🌟(#63) 스웨거 수정 및 알림 Entity

- src/main/java/com/shinhan/knockknock/domain/dto/LoginUserRequest.java
> 🌟(#91) LoginType 중복제거

- src/main/java/com/shinhan/knockknock/domain/dto/IdLoginUserRequest.java
- src/main/java/com/shinhan/knockknock/domain/dto/SimpleLoginUserRequest.java
- src/test/java/com/shinhan/knockknock/controller/AuthControllerTest.java
- src/test/java/com/shinhan/knockknock/service/WelfareBookServiceTest.java
- src/test/java/com/shinhan/knockknock/service/WelfareServiceTest.java
> 🌟(#91 ) 테스트 코드 수정

- src/main/java/com/shinhan/knockknock/config/SecurityConfig.java
- src/main/java/com/shinhan/knockknock/controller/MatchController.java
- src/main/java/com/shinhan/knockknock/controller/UserController.java
- src/main/java/com/shinhan/knockknock/domain/dto/ReadUserResponse.java
- src/main/java/com/shinhan/knockknock/domain/dto/SimpleLoginUserRequest.java
- src/main/java/com/shinhan/knockknock/domain/dto/UpdateUserRequest.java
- src/main/java/com/shinhan/knockknock/domain/dto/UserValidationRequest.java
- src/main/java/com/shinhan/knockknock/domain/entity/MatchEntity.java
- src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
- src/main/java/com/shinhan/knockknock/repository/MatchRepository.java
- src/main/java/com/shinhan/knockknock/service/MatchService.java
- src/main/java/com/shinhan/knockknock/service/MatchServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/UserService.java
- src/main/java/com/shinhan/knockknock/service/UserServiceImpl.java
- src/test/java/com/shinhan/knockknock/controller/AuthControllerTest.java
- src/test/java/com/shinhan/knockknock/controller/MatchControllerTest.java
- src/test/java/com/shinhan/knockknock/controller/UserControllerTest.java
- src/test/java/com/shinhan/knockknock/service/UserServiceTest.java
- 마이페이지 회원 정보 조회 구현
- 회원 정보 수정 구현
- 회원 탈퇴 구현
> 🌟(#96 ) 회원 정보 수정 및 탈퇴 구현

- src/main/java/com/shinhan/knockknock/config/WebConfig.java
> 🌟 CORS 설정 추가

- src/main/java/com/shinhan/knockknock/config/WebConfig.java
> 🌟WebConfig 수정

- src/main/java/com/shinhan/knockknock/domain/dto/UpdateUserRequest.java
- src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
- java.util.date -> sql.date로 변경
> 🌟(#96 ) 회원 entity date 타입 변경

- src/main/java/com/shinhan/knockknock/controller/WelfareBookController.java
- src/main/java/com/shinhan/knockknock/domain/dto/welfarebook/CreateWelfareBookRequest.java
- src/main/java/com/shinhan/knockknock/domain/entity/WelfareBookEntity.java
- src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookService.java
- src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookServiceImpl.java
- src/test/java/com/shinhan/knockknock/controller/WelfareBookControllerTest.java
- userEntity 데이터 저장 안되는 것 수정
- 변수 타입 수정
> 🌟(#111 ) 복지예약 코드 수정

- src/main/java/com/shinhan/knockknock/config/SwaggerConfig.java
- src/main/java/com/shinhan/knockknock/domain/dto/conversation/ChatbotResponse.java
- src/main/java/com/shinhan/knockknock/domain/dto/conversation/ConversationResponse.java
- src/main/java/com/shinhan/knockknock/service/conversation/ChainService.java
- src/main/java/com/shinhan/knockknock/service/conversation/ChatbotService.java
- src/main/java/com/shinhan/knockknock/service/conversation/ConversationService.java
- src/main/java/com/shinhan/knockknock/service/conversation/PromptService.java
- src/main/java/com/shinhan/knockknock/service/conversation/TextResponseService.java
- src/main/resources/application.properties
- src/main/resources/prompts/basic.prompt
- 말동무 response에 바로가기, 예약 정보 추가
-
> 🌟(#56 ) 말동무 response에 바로가기, 예약 정보 추가

- .github/workflows/main.yml
> 🌟(#145 ) main.yml 수정

- .github/workflows/main.yml
> 🌟(#146) main.yml 수정

- src/main/java/com/shinhan/knockknock/controller/ConversationRoomController.java
- src/main/java/com/shinhan/knockknock/domain/entity/CardIssueEntity.java
- src/main/java/com/shinhan/knockknock/repository/CardRepository.java
- src/main/java/com/shinhan/knockknock/repository/ConversationRoomRepository.java
- src/main/java/com/shinhan/knockknock/service/consumption/ConsumptionService.java
- src/main/java/com/shinhan/knockknock/service/consumption/ConsumptionServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/conversation/ConversationRoomServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/conversation/ConversationService.java
- src/main/java/com/shinhan/knockknock/service/conversation/TextResponseService.java
- src/main/java/com/shinhan/knockknock/service/conversation/TokenService.java
- src/main/java/com/shinhan/knockknock/service/conversation/task/ClassificationTaskService.java
- src/main/java/com/shinhan/knockknock/service/conversation/task/DailyConversationTaskService.java
- src/main/java/com/shinhan/knockknock/service/conversation/task/FinanceTaskService.java
- src/main/java/com/shinhan/knockknock/service/conversation/task/GreetingTaskService.java
- src/main/java/com/shinhan/knockknock/service/conversation/task/WelfareTaskService.java
- src/main/resources/prompts/basic.prompt
- src/main/resources/prompts/classification.prompt
- src/main/resources/prompts/finance.prompt
- src/main/resources/prompts/welfare.prompt
- src/test/java/com/shinhan/knockknock/service/ConversationLogTest.java
- src/test/java/com/shinhan/knockknock/service/ConversationRoomTest.java
- src/test/java/com/shinhan/knockknock/service/WelfareBookServiceTest.java
- src/test/java/com/shinhan/knockknock/service/WelfareServiceTest.java
> 🌟(#144 ) 말동무 Task 파일 분리 및 예외처리

- src/main/java/com/shinhan/knockknock/domain/dto/match/CreateMatchResponse.java
- src/main/java/com/shinhan/knockknock/domain/dto/match/UpdateMatchRequest.java
- src/main/java/com/shinhan/knockknock/service/match/MatchService.java
- src/main/java/com/shinhan/knockknock/service/match/MatchServiceImpl.java
- src/test/java/com/shinhan/knockknock/controller/MatchControllerTest.java
- request, response 데이터 추가
- service 수정
> 🌟(#47 ) 매칭 조회 및 응답 수정

- src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
- src/main/java/com/shinhan/knockknock/domain/dto/cardhistory/ReadCardHistoryResponse.java
- src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryService.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
- 카드내역 기간별 조회 추가
- 복지예약 500오류 수정
> 🌟(#103 ) 카드내역, 복지예약 코드 수정

- src/main/java/com/shinhan/knockknock/config/SwaggerConfig.java
- src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
> 🌟(#103 ) swagger https 주소변경

- src/main/java/com/shinhan/knockknock/controller/WelfareBookController.java
- src/main/java/com/shinhan/knockknock/domain/dto/welfarebook/CreateWelfareBookRequest.java
- src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookService.java
- src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookServiceImpl.java
> 🌟(#103) 복지예약 수정중

- src/main/java/com/shinhan/knockknock/controller/CardController.java
- src/main/java/com/shinhan/knockknock/domain/dto/card/ReadMemberInfo.java
- src/main/java/com/shinhan/knockknock/repository/UserRepository.java
- src/main/java/com/shinhan/knockknock/service/card/CardIssueService.java
- src/main/java/com/shinhan/knockknock/service/card/CardIssueServiceImpl.java
> 🌟(#167 ) 회원 정보 조회

- src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
- src/main/java/com/shinhan/knockknock/domain/dto/cardhistory/DetailCardHistoryResponse.java
- src/main/java/com/shinhan/knockknock/domain/dto/cardhistory/ReadCardHistoryResponse.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryService.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookServiceImpl.java
- 거래취소 만듦
- 카드내역 조회시 불러오는 데이터 수정
> 🌟(#175 ) 카드 내역 코드 수정

- src/main/java/com/shinhan/knockknock/config/SwaggerConfig.java
- src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryService.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
> 🌟swagger local path 추가

- src/main/java/com/shinhan/knockknock/config/WebConfig.java
- src/main/java/com/shinhan/knockknock/interceptor/ApiLoggingInterceptor.java
> [Feat]: 로그 추가

- src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryService.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
> 🌟cardhistory detail조회 수정

- src/main/java/com/shinhan/knockknock/controller/WelfareBookController.java
- src/main/java/com/shinhan/knockknock/domain/dto/cardhistory/DetailCardHistoryResponse.java
- src/main/java/com/shinhan/knockknock/domain/dto/welfare/ReadWelfareResponse.java
- src/main/java/com/shinhan/knockknock/domain/dto/welfarebook/CreateWelfareBookRequest.java
- src/main/java/com/shinhan/knockknock/repository/CardCategoryRepository.java
- src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
- src/main/java/com/shinhan/knockknock/repository/CardRepository.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/welfare/WelfareService.java
- src/main/resources/sql/user.sql
> 🌟복지 예약, 복지 리스트 코드 수정

- src/main/java/com/shinhan/knockknock/domain/dto/card/CreateCardIssueRequest.java
> Bugfix card family

- src/main/java/com/shinhan/knockknock/config/CustomSqlLoader.java
- src/main/java/com/shinhan/knockknock/repository/CardIssueRepository.java
- src/main/java/com/shinhan/knockknock/service/card/CardIssueServiceImpl.java
- src/main/resources/sql/card.sql
- src/main/resources/sql/cardhistory.sql
- src/main/resources/sql/user.sql
> 🌟(#200 ) sql문

- src/main/resources/sql/cardissue.sql
> 🌟(#200 ) sql

- src/main/java/com/shinhan/knockknock/service/card/CardIssueServiceImpl.java
> ## 🌟(#200 ) 코드 수정 

- src/main/java/com/shinhan/knockknock/domain/dto/card/ReadCardIssueResponse.java
- src/main/java/com/shinhan/knockknock/service/card/CardIssueService.java
> 🌟(#200 ) 수정 

- src/main/java/com/shinhan/knockknock/config/SchedulerConfig.java
- src/main/java/com/shinhan/knockknock/controller/CardController.java
- src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
- src/main/java/com/shinhan/knockknock/service/card/CardIssueServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/card/CardServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/consumption/ConsumptionServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/notification/NotificationServiceImpl.java
- 카드 발급 Kname, Phone null 처리
- 소비리포트 카테고리값 null 처리
- 이상 징후 알림 일부 구현
> [bugfix] 카드 발급, 소비리포트

- src/main/java/com/shinhan/knockknock/config/SecurityConfig.java
- src/main/java/com/shinhan/knockknock/controller/CardHistoryDataController.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
- src/main/resources/static/card-history.html
- src/main/resources/static/login.html
> 🌟프론트 cardHistory data넣는 페이지 제작

- src/main/java/com/shinhan/knockknock/controller/CardController.java
- src/main/java/com/shinhan/knockknock/domain/dto/card/ReadIsCardResponse.java
- src/main/java/com/shinhan/knockknock/repository/CardRepository.java
- src/main/java/com/shinhan/knockknock/service/card/CardService.java
- src/main/java/com/shinhan/knockknock/service/card/CardServiceImpl.java
> 🌟(#22 ) 카드 유무 기능

- src/main/java/com/shinhan/knockknock/domain/dto/conversation/ConsumptionReportResponse.java
- src/main/java/com/shinhan/knockknock/domain/dto/conversation/ConversationResponse.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryService.java
- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
- src/main/java/com/shinhan/knockknock/service/conversation/ChainService.java
- src/main/java/com/shinhan/knockknock/service/conversation/ConversationService.java
- src/main/java/com/shinhan/knockknock/service/conversation/PromptService.java
- src/main/java/com/shinhan/knockknock/service/conversation/TokenService.java
- src/main/java/com/shinhan/knockknock/service/conversation/task/FinanceTaskService.java
- src/main/java/com/shinhan/knockknock/service/conversation/task/WelfareTaskService.java
- src/main/resources/prompts/consumption.prompt
- src/main/resources/prompts/finance.prompt
- src/main/resources/prompts/reservation.prompt
- src/test/java/com/shinhan/knockknock/service/WelfareBookServiceTest.java
> 🌟(#144 ) 말동무 소비내역 조회 추가

- src/main/java/com/shinhan/knockknock/service/conversation/task/WelfareTaskService.java
> 🌟(#144 ) 말동무 바로가기 수정

- src/main/java/com/shinhan/knockknock/config/SchedulerConfig.java
- src/main/java/com/shinhan/knockknock/controller/CardController.java
- src/main/java/com/shinhan/knockknock/repository/CardRepository.java
- src/main/java/com/shinhan/knockknock/service/card/CardServiceImpl.java
> 🌟(#22) 카드 유무 코드 수정

- src/main/java/com/shinhan/knockknock/config/SchedulerConfig.java
- src/main/java/com/shinhan/knockknock/service/card/CardServiceImpl.java
> 🌟(#200 ) 카드 유무 수정

- src/main/java/com/shinhan/knockknock/config/SchedulerConfig.java
- src/main/java/com/shinhan/knockknock/repository/ConversationRoomRepository.java
- src/main/resources/sql/cardhistory.sql
> 🌟(#234) 이상징후 조건 추가

- src/main/java/com/shinhan/knockknock/auth/JwtProvider.java
- src/main/java/com/shinhan/knockknock/controller/UserController.java
- src/main/java/com/shinhan/knockknock/service/user/UserServiceImpl.java
> 🌟(#95 ) 전화번호 중복 체크 삭제

- src/main/java/com/shinhan/knockknock/service/card/CardServiceImpl.java
> 🌟(#237 ) 카드 리스트 중복 제거

- src/main/java/com/shinhan/knockknock/auth/JwtAuthenticationFilter.java
- src/main/java/com/shinhan/knockknock/auth/JwtProvider.java
- src/main/java/com/shinhan/knockknock/controller/AuthController.java
- src/main/java/com/shinhan/knockknock/service/user/AuthService.java
- Refresh Token 없어도 로그아웃 가능하게 수정
- Refresh Token 없을시 예외처리 수정
> 🌟(#124 ) 로그아웃 및 필터 예외처리

- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
> 🌟숫자 단위 , 추가

- src/main/java/com/shinhan/knockknock/service/user/UserServiceImpl.java
> 🌟(#96 ) 정보수정 주소 null 처리

- src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
> 🌟알림 카테고리 이름 변경

- src/main/java/com/shinhan/knockknock/service/card/CardServiceImpl.java
- src/main/resources/sql/card.sql
> 🌟(#241) 일부 수정

- src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookServiceImpl.java
- src/main/resources/sql/user.sql
- user.sql 데이터 수정
- 복지 예약 주소 null 처리
> 🌟(#96 ) 회원 데이터 수정
